name: Build TS-DAR source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: ["3.9","3.10"]
        os: 
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
    - name: Install required packages 
      run: |
        python -m pip install --upgrade pip
    - name: Pip install
      run: |
        python -m pip install .
        
